version: '3.7'

services:

    api:
        container_name: api_container
        stdin_open: true
        build: .
        ports:
            - ${PORT}:${PORT}
        tmpfs:
            - /home/temp
        volumes:
            - .:/home/services
        depends_on:
            -   database

    database:
        image: postgres
        container_name: database_container
        restart: always
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - pgdata:/data/postgres


volumes:
    pgdata: